
# SEO settings
title: "Sean"
title2: "Kwon" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://seankwon.github.io/personalWebsite # site url
baseurl: "/personalWebsite" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-90747189-1
repo: http://github.com/seankwon/personalWebsite
disqus_shortname: "seankwon"
twitter_username: "hyuknhim"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Sean Kwon"
  job      : "Software Engineer"
  bio      : "I sometimes write a few things"
  thumb    : /images/author.jpg
  email    : seankwn12@gmail.com
  url      : http://seankwon.github.io
  github   : http://github.com/seankwon
  twitter  : http://twitter.com/hyuknhim
  facebook : https://www.facebook.com/seankwn
  linkedin : http://linkedin.com/in/sean-kwon-69339067

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@hyuknhim"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
